# Generated by Django 4.1.5 on 2023-01-20 10:59

from django.db import migrations, models
import django.db.models.deletion
import mptt.fields


class Migration(migrations.Migration):

    dependencies = [
        ('beauty_blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='main',
            field=models.BooleanField(default=False, verbose_name='Главная'),
        ),
        migrations.AlterField(
            model_name='category',
            name='parent',
            field=mptt.fields.TreeForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='children', to='beauty_blog.category', verbose_name='Родительская категория'),
        ),
    ]
